### ISSUE TITLE
Table for meals (MealsTable) (Epic #1)

### ISSUE THREAD

**Issue by haohuant** [ucsb-cs156-f24/proj-dining-f24-15#16]
# Frontend 1: table for meals (MealsTable)

Build a table that can display meals as returned by the `GET /api/diningcommons/:date-time/:dining-commons-code` endpoint.   Each meal should link to a page /diningcommons/:date-time/:dining-commons-code/:meal

Likely to create:
- fixtures
- table
- table test
- util files?

# Dependencies

Complete the following issues first:
* Create fixtures for Meals
* Set up GitHub Pages (for Storybook)

# Acceptance Criteria:

- [x] A table called `MealsTable` is visible in the storybook
      accessible on the Github Pages link.
      
- [x] The table has all the fields that are in the database table 
      labelled with user-friendly names corresponding to the database table column names.

- [x] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new table (since this is a frontend change).

- [x] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `MealsTable` component.

# Implementation Details

- [x] Under `frontend/src/main/components/Meals/` create a file called `MealsTable.js`,
      modelled after the files `RestaurantTable.js` and `UCSBDatesTable.js`

- [x] Under `frontend/src/test/components/Meals/` create a file called `MealsTable.test.js` 
      modelled after the files `RestaurantTable.test.js and `UCSBDatesTable.test.js`.

- [x] Under `frontend/src/stories/components/Meals/` create a file called `MealsTable.stories.js`,
      modelled after the files `RestaurantTable.stories.js` and `UCSBDatesTable.stories.js`.
        
# Notes

* For *this* issue, tt is not necessary that the table be linked to a
  page that connects it to the backend; that will be done in a later issue.

* This issue illustrates how it is possible to create at least part of the frontend
  for a feature even if/when the backend is not yet complete.

# Reminders (all from `frontend` directory):

* Always start by setting the node version with `nvm use 20.17.0`
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/UCSBOrganization/UCSBOrganizationForm.js`

# What to do next

Do a PR, following all of the usual steps (title, description, `Closes #n` text,
dragging issue to "In Review", requesting reviewers).

Check to see if any fellow team members PRs need to be reviewed.

Then, assign yourself the issue "Copy Placeholders for `UCSBOrganization` pages; add to App.js/AppNavbar.js"

Follow all the usual steps (assign to self, drag to "In Progress", start new branch.)
