### ISSUE TITLE
Create database table for reviews (EPIC #2)

### ISSUE THREAD

**Issue by haohuant** [ucsb-cs156-f24/proj-dining-f24-15#6]
Subtask of #2 

# Backend 1: Create database table for reviews

- id
- Student user id (just the number in the users table)
- DiningCommons
- Meal
- Menu Item
- StationName
- Date item was served
- Status (initally "Awaiting Moderation")
- userid of moderator if approved/rejected (initially null)
- Moderator comments (initally null)
- CreatedDate
- LastEditedDate

# Acceptance Criteria:

- [x] There is an `@Entity` class called DiningCommonsReview.java
- [x] There is a `@Repository` class called DiningCommonsReviewRepository.java
- [x] There is a database migration file called DiningCommonsReview.json
- [x] When you start up the repo on localhost, you can see the table
      using the H2 console (see the file [`docs/h2-database.md`](/ucsb-cs156-f24/STARTER-team01//blob/main/docs/h2-database.md) for 
      instructions.)
- [x] When you deploy the app to Dokku, you can see the table
      using the `dokku postgres:connect team01-db` command
      (use `\dt` to list the tables) (See <https://ucsb-cs156.github.io/topics/dokku/postgres_database.html#postgres-command-line> for more info.)

# Ex

https://github.com/ucsb-cs156-f24/team01-f24-15/issues/8#issue-2595921695

You'll probably need:
- @Entity class
- @Repository class
- database migration file
- check to see if the table is in h2
- check to see if the table is in Dokku using the dokku postgres:connect team01-db command (use \dt to list the tables) (See https://ucsb-cs156.github.io/topics/dokku/postgres_database.html#postgres-command-line for more info.)

# What to do next

Do a PR, following all of the usual steps (title, description, Closes #n text, dragging issue to "In Review", requesting reviewers).

Check to see if any fellow team members PRs need to be reviewed.

Then, assign yourself the next incomplete issue (Controllers).

Follow all the usual steps (assign to self, drag to "In Progress", **_start new branch_**.)

**Comment by pconrad** [comment]
HEADS UP!  There is a significant change to the database design that you need to be aware of.  Please consult

https://github.com/ucsb-cs156-f24/proj-dining-f24-15/issues/2

for the updates!
